version: "3.8"
services:
  app:
    build:
      context: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=levorg_database
      - DB_USER=root
      - DB_PASSWORD=secretpassword
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: levorg_database
